
aws:
  region: us-east-1  # Change to your preferred AWS region
  credentials:
    access-key: dummyAccessKey
    secret-key: dummySecretKey
  ses:
    endpoint: http://localhost:8000 # Local SES endpoint
    credentials:
      access-key: dummyAccessKey
      secret-key: dummySecretKey
    sender-email: no-reply@bulbeni.online


dynamodb:
  endpoint: http://localhost:8000  # Local DynamoDB endpoint

spring:
  jackson:
    deserialization:
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT : true
  mail:
    host: smtp.gmail.com
    port: 587
    username: bulbeni.online.tr@gmail.com
    password: jpol znig jscs jowg
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mail:
  sender: bulbeni.online.tr@gmail.com  # Same as spring.mail.username

jwt:
  secret: your-very-secure-secret-key-1234567890  # Replace with a long, random string (at least 32 characters)
  expiration: 3600000 # 1 hour in milliseconds (3600 seconds * 1000)
  #expiration : 86400000 # 24 hours

logging:
  level:
    tr.akb.price_tracker_backend.security: DEBUG
    org.springframework.security: DEBUG