
aws:
  region: us-east-1  # Change to your preferred AWS region
  credentials:
    access-key: dummyAccessKey
    secret-key: dummySecretKey

dynamodb:
  endpoint: http://localhost:8000  # Local DynamoDB endpoint

spring:
  jackson:
    deserialization:
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT : true

jwt:
  secret: your-very-secure-secret-key-1234567890  # Replace with a long, random string (at least 32 characters)

logging:
  level:
    tr.akb.price_tracker_backend.security: DEBUG
    org.springframework.security: DEBUG